/** @type {import('next').NextConfig} */
const nextConfig = {
    env: {
        VERSION: process.env.VERSION,
        DB_NAME: process.env.DB_NAME,
        RPC_ENDPOINT: process.env.RPC_ENDPOINT,
        SINGLE_COLLATERAL_PACKAGE: process.env.SINGLE_COLLATERAL_PACKAGE,
        SINGLE_COLLATERAL_PACKAGE_ORIGIN: process.env.SINGLE_COLLATERAL_PACKAGE_ORIGIN,
        SINGLE_COLLATERAL_MANAGER_CAP: process.env.SINGLE_COLLATERAL_MANAGER_CAP,
        SINGLE_COLLATERAL_REGISTRY: process.env.SINGLE_COLLATERAL_REGISTRY,
        SINGLE_COLLATERAL_DEPOSIT_VAULT_REGISTRY: process.env.SINGLE_COLLATERAL_DEPOSIT_VAULT_REGISTRY,
        SINGLE_COLLATERAL_BID_VAULT_REGISTRY: process.env.SINGLE_COLLATERAL_BID_VAULT_REGISTRY,
        ORACLE_PACKAGE: process.env.ORACLE_PACKAGE,
        ORACLE_MANAGER_CAP: process.env.ORACLE_MANAGER_CAP,
        SUI_ORACLE: process.env.SUI_ORACLE,
        CETUS_ORACLE: process.env.CETUS_ORACLE
    }
}

module.exports = nextConfig
